name: Go

on:
  release:
    types: [ created ]

jobs:
  releases-linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ "386", amd64, arm64, ppc64, ppc64le, mips, mipsle, mips64, mips64le ]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.18
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/distr"
          binary_name: "wscan"
          overwrite: true

  releases-windows:
    name: Windows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ windows ]
        goarch: [ "386", amd64 ]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.18
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/distr"
          binary_name: "wscan"
          overwrite: true

  releases-android:
    name: Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ android  ]
        goarch: [ "386", amd64, arm64 ]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.18
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/distr"
          binary_name: "wscan"
          overwrite: true
